name: Bug Report
description: Report a bug found on the Kusogaki Crossdoku site.
body:
  - type: textarea
    id: description
    attributes:
      label: Description and reproduction of the issue
    validations:
      required: true
